[package]
name = "orbrs"
version = "0.1.0"
authors = ["patrickisroman <>"]
edition = "2018"

[profile.release]
opt-level = 3

[dependencies]
image = "0.23.10"
imageproc = "*"
rand = "0.7.3"
bitvector = "0.1.5"
cgmath = "0.15.0"

